version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data6/
    env_file:
      - ../configuration/.env
  api:
    build:
      context: ../ 
      dockerfile: ./configuration/Dockerfile
    restart: always
    env_file:
      - ../configuration/.env 
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
volumes:
  postgres_data: