# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"\x99\x01\n\rConfigMessage\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07is_used\x18\x03 \x01(\x05\x12!\n\x04keys\x18\x04 \x03(\x0b\x32\x13.ConfigMessage.Keys\x1a\x32\n\x04Keys\x12\x13\n\x0bservice_key\x18\x01 \x01(\t\x12\x15\n\rservice_value\x18\x02 \x01(\tb\x06proto3'
)




_CONFIGMESSAGE_KEYS = _descriptor.Descriptor(
  name='Keys',
  full_name='ConfigMessage.Keys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_key', full_name='ConfigMessage.Keys.service_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service_value', full_name='ConfigMessage.Keys.service_value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=168,
)

_CONFIGMESSAGE = _descriptor.Descriptor(
  name='ConfigMessage',
  full_name='ConfigMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='ConfigMessage.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='ConfigMessage.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_used', full_name='ConfigMessage.is_used', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='ConfigMessage.keys', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGMESSAGE_KEYS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=168,
)

_CONFIGMESSAGE_KEYS.containing_type = _CONFIGMESSAGE
_CONFIGMESSAGE.fields_by_name['keys'].message_type = _CONFIGMESSAGE_KEYS
DESCRIPTOR.message_types_by_name['ConfigMessage'] = _CONFIGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigMessage = _reflection.GeneratedProtocolMessageType('ConfigMessage', (_message.Message,), {

  'Keys' : _reflection.GeneratedProtocolMessageType('Keys', (_message.Message,), {
    'DESCRIPTOR' : _CONFIGMESSAGE_KEYS,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:ConfigMessage.Keys)
    })
  ,
  'DESCRIPTOR' : _CONFIGMESSAGE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ConfigMessage)
  })
_sym_db.RegisterMessage(ConfigMessage)
_sym_db.RegisterMessage(ConfigMessage.Keys)


# @@protoc_insertion_point(module_scope)
