# Generated by Django 4.1.2 on 2022-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceversion',
            name='version',
            field=models.TextField(),
        ),
    ]
