# Generated by Django 4.1.2 on 2022-10-25 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_alter_serviceversion_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicekey',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configs.service'),
        ),
    ]
