# Generated by Django 4.1.2 on 2022-10-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_servicekey_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicekey',
            name='is_used',
        ),
        migrations.AddField(
            model_name='serviceversion',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
