# Generated by Django 4.1.2 on 2022-10-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_alter_servicekey_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicekey',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configs.service'),
            preserve_default=False,
        ),
    ]
